
services:
  test_task_postgres:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      test_task_postgres:
        condition: service_healthy

  app:
    build: .
    command: sh -c "poetry run alembic upgrade head && poetry run dev"
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
    ports:
      - "8000:8000"
    depends_on:
      test_task_postgres:
        condition: service_healthy

volumes:
  postgres_data:
